version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
